
"""
Constants for accounts app.
Contains centralized lists of Colleges and Branches.
"""

COLLEGE_NAMES = [
    # Indira Group
    "School of Business, Indira University",
    "School of Commerce and Economics, Indira University",
    "School of Information Technology, Indira University",
    "School of Pharmacy, Indira University",
    "School of Liberal Arts, Indira University",
    "Indira Institute of Management Pune",
    "Indira College of Engineering & Management",
    "Indira College of Pharmacy",
    "Indira College of Commerce & Science",
    "Indira School of Aviation",
    "Indira School of Business Studies (ISBS - PGDM)",
    "Indira Global School of Business",
    "Indira School of Communication",

    # Sangamner
    "Sangamner Nagarpalika Arts, DJ Malpani Commerce and BN Sarada Science College",
    "Amrutvahini College of Engineering",
    "Amrutvahini College of Pharmacy",
    "Amrutvahini Polytechnic",
    "Amrutvahini Institute of Management and Business Administration",
    "S.M.B.T Dental College & Hospital, Sangamner",
    "Shramshakti College of Agriculture, Sangamner",
    "Shri Omkarnath Malpani Law College, Sangamner",
    "Matoshri Radha College of Pharmacy, Sangamner",
    "Ashvin College of Pharmacy, Sangamner",
    "Vrindavan College of Agriculture, Sangamner",
    "Kai Sau Sunitatati Eknatharao Dhakane Polytechnic, Sangamner",
    "Dr Bhanudas Dere Ayurved Medical College, Sangamner",
    "Trimurti Chitrakala Mahavidyalay, Sangamner",
    "Sangamner College of Education",

    # Pune & Others
    "Savitribai Phule Pune University",
    "Symbiosis International University, Pune",
    "Bharati Vidyapeeth University, Pune",
    "College of Engineering Pune (COEP)",
    "Symbiosis Institute of Technology",
    "MIT World Peace University, Pune",
    "Vishwakarma Institute of Technology, Pune",
    "Pune Institute of Computer Technology (PICT)",
    "Defence Institute of Advanced Technology (DIAT), Pune",
    "Army Institute of Technology (AIT), Pune",
    "Bharati Vidyapeeth College of Engineering, Pune",
    "DY Patil University, Pune",
    "Fergusson College, Pune",
    "ILS Law College, Pune",
    "AISSMS College of Engineering, Pune",
    "AISSMS College of Hotel Management & Catering Technology",
    "National Institute of Bank Management (NIBM), Pune",
    "Symbiosis Institute of Business Management (SIBM), Pune",
    "Pune Institute of Business Management (PIBM)",
    "National Insurance Academy (NIA), Pune",
    "FLAME University, Pune",
    "Gokhale Institute of Politics and Economics, Pune",
    "Film and Television Institute of India (FTII), Pune",
    "Mahindra United World College of India, Pune",
    "Nowrosjee Wadia College, Pune",
    "Ness Wadia College of Commerce, Pune",
    "MES Garware College of Commerce, Pune",
    "PES Modern College of Engineering, Pune",
    "ABhinav Education Society College of Pharmacy, Pune",
    "ALARD Institute of Management Sciences, Pune",
    "Anand Medical Foundation’s Nursing Institute, Pune",
    "Army Law College, Pune",
    "ABMSS PY Rao Chavan Law College, Pune",
    "A K Khan Law College, Pune"
]

BRANCH_CHOICES = [
    # Engineering & Technology
    ("Information Technology", "Information Technology"),
    ("Artificial Intelligence", "Artificial Intelligence"),
    ("Data Science", "Data Science"),
    ("Mechanical Engineering", "Mechanical Engineering"),
    ("Electrical Engineering", "Electrical Engineering"),
    ("Electronics and Communication Engineering", "Electronics and Communication Engineering"),
    ("Civil Engineering", "Civil Engineering"),
    ("Robotics", "Robotics"),
    ("Mechatronics", "Mechatronics"),
    ("Automation and Robotics Engineering", "Automation and Robotics Engineering"),
    ("Architecture", "Architecture"),
    
    # Science (B.Sc)
    ("B.Sc Mathematics", "B.Sc Mathematics"),
    ("B.Sc Physics", "B.Sc Physics"),
    ("B.Sc Statistics", "B.Sc Statistics"),
    ("B.Sc Computer Science", "B.Sc Computer Science"),
    ("B.Sc Artificial Intelligence and Data Science", "B.Sc Artificial Intelligence and Data Science"),
    ("B.Sc Data Science", "B.Sc Data Science"),
    ("B.Sc Cyber Security", "B.Sc Cyber Security"),

    # Commerce & Management
    ("B.Com", "B.Com"),
    ("B.Com Financial Markets", "B.Com Financial Markets"),
    ("B.Com Accounting and Finance", "B.Com Accounting and Finance"),
    ("B.Com Business Administration", "B.Com Business Administration"),
    ("BBA", "BBA"),
    ("BBA Innovation and Entrepreneurship", "BBA Innovation and Entrepreneurship"),
    ("BBA Digital Marketing", "BBA Digital Marketing"),
    ("BBA Financial Management", "BBA Financial Management"),
    ("BBA Marketing Management", "BBA Marketing Management"),
    ("BBA Human Resource Management", "BBA Human Resource Management"),
    ("BBA Banking and Financial Services", "BBA Banking and Financial Services"),
    ("BBM", "BBM"),
    ("Business Analytics", "Business Analytics"),
    ("Digital Marketing", "Digital Marketing"),
    ("E Commerce", "E Commerce"),
    ("Entrepreneurship", "Entrepreneurship"),

    # Professional Courses
    ("CA", "CA"),
    ("CS", "CS"),
    ("CMA", "CMA"),
    ("ACCA", "ACCA"),
    ("CFA", "CFA"),

    # Arts & Social Sciences
    ("BA", "BA"),
    ("Economics", "Economics"),
    ("Political Science", "Political Science"),
    ("History", "History"),
    ("Sociology", "Sociology"),
    ("Psychology", "Psychology"),
    ("English", "English"),
    ("Law", "Law"),
    ("Journalism", "Journalism"),
    ("Mass Communication", "Mass Communication"),
    ("Public Administration", "Public Administration"),
    ("International Relations", "International Relations"),
    ("Social Work", "Social Work"),

    # Medical & Health Sciences
    ("MBBS", "MBBS"),
    ("BDS", "BDS"),
    ("BAMS", "BAMS"),
    ("BHMS", "BHMS"),
    ("BUMS", "BUMS"),
    ("Nursing", "Nursing"),
    ("B.Pharm", "B.Pharm"),
    ("D.Pharm", "D.Pharm"),
    ("Pharm.D", "Pharm.D"),
    ("Veterinary Science", "Veterinary Science"),
    ("Biotechnology", "Biotechnology"),
    ("Microbiology", "Microbiology"),
    ("Forensic Science", "Forensic Science"),
    ("Physiotherapy", "Physiotherapy"),
    ("Nutrition and Dietetics", "Nutrition and Dietetics"),
    ("Radiology", "Radiology"),
    ("Medical Lab Technology", "Medical Lab Technology"),
    ("Paramedical Sciences", "Paramedical Sciences"),

    # Others
    ("BCA", "BCA"),
    ("Actuarial Science", "Actuarial Science"),
    ("Commercial Pilot", "Commercial Pilot"),
    ("NDA", "NDA"),
    ("Fashion Designing", "Fashion Designing"),
    ("Interior Designing", "Interior Designing"),
    ("Graphic Design", "Graphic Design"),
    ("Animation and VFX", "Animation and VFX"),
    ("Fine Arts", "Fine Arts"),
    ("Film Making", "Film Making"),
    ("Music", "Music"),
    ("Performing Arts", "Performing Arts"),
    ("Polytechnic", "Polytechnic"),
    ("ITI", "ITI"),
    ("Hotel Management", "Hotel Management"),
    ("Culinary Arts", "Culinary Arts"),
    ("Aviation", "Aviation"),
    ("Travel and Tourism", "Travel and Tourism"),
    ("Event Management", "Event Management"),
    ("Sports Science", "Sports Science"),
    ("Fitness and Nutrition", "Fitness and Nutrition"),
    ("Foreign Languages", "Foreign Languages"),
    ("Game Development", "Game Development"),

    # Post Graduate
    ("MBA Human Resource Management", "MBA Human Resource Management"),
    ("MBA Marketing Management", "MBA Marketing Management"),
    ("MBA Business Analytics", "MBA Business Analytics"),
    ("MBA Financial Management", "MBA Financial Management"),
    ("MBA Operations and Supply Chain Management", "MBA Operations and Supply Chain Management"),
    ("M.Sc Computer Science", "M.Sc Computer Science"),
    ("M.Sc Computer Application", "M.Sc Computer Application"),
    ("M.E / M.Tech Mechanical Engineering", "M.E / M.Tech Mechanical Engineering"),
    ("M.E / M.Tech Civil Engineering", "M.E / M.Tech Civil Engineering"),
    ("M.E / M.Tech Computer Engineering", "M.E / M.Tech Computer Engineering"),
    ("M.Pharm Pharmaceutics", "M.Pharm Pharmaceutics"),
    ("M.Pharm Pharmaceutical Quality Assurance", "M.Pharm Pharmaceutical Quality Assurance"),
    ("M.Pharm Pharmacology", "M.Pharm Pharmacology"),

    # Ph.D
    ("Ph.D Pharmaceutical Sciences", "Ph.D Pharmaceutical Sciences"),
    ("Ph.D Commerce and Economics", "Ph.D Commerce and Economics"),
    ("Ph.D Information Technology", "Ph.D Information Technology"),
    ("Ph.D Business Studies", "Ph.D Business Studies"),
    ("Ph.D Liberal Arts", "Ph.D Liberal Arts")
]
