# Generated by Django 6.0 on 2025-12-27 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('total_users', models.IntegerField(default=0, verbose_name='Total Users')),
                ('total_quizzes', models.IntegerField(default=0, verbose_name='Total Quizzes')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Total Attempts')),
                ('avg_response_time_ms', models.FloatField(default=0.0, verbose_name='Avg Response Time (ms)')),
                ('error_rate', models.FloatField(default=0.0, verbose_name='Error Rate %')),
                ('uptime_percentage', models.FloatField(default=99.9, verbose_name='Uptime %')),
                ('daily_active_users', models.IntegerField(default=0, verbose_name='DAU')),
                ('weekly_active_users', models.IntegerField(default=0, verbose_name='WAU')),
                ('monthly_active_users', models.IntegerField(default=0, verbose_name='MAU')),
                ('avg_sessions_per_user', models.FloatField(default=0.0, verbose_name='Avg Sessions/User')),
                ('avg_session_duration', models.IntegerField(default=0, verbose_name='Avg Session (s)')),
                ('most_attempted_quiz', models.CharField(blank=True, max_length=255, verbose_name='Most Attempted Quiz')),
                ('most_attempted_category', models.CharField(blank=True, max_length=255, verbose_name='Most Attempted Category')),
            ],
            options={
                'verbose_name': 'Platform Metrics',
                'verbose_name_plural': 'Platform Metrics',
                'db_table': 'analytics_platformmetrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('total_users', models.IntegerField(default=0, verbose_name='Total Users')),
                ('active_users', models.IntegerField(default=0, verbose_name='Active Users (24h)')),
                ('new_users', models.IntegerField(default=0, verbose_name='New Users')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Total Attempts')),
                ('successful_attempts', models.IntegerField(default=0, verbose_name='Successful Attempts')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='Failed Attempts')),
                ('quizzes_created', models.IntegerField(default=0, verbose_name='Quizzes Created')),
                ('quizzes_published', models.IntegerField(default=0, verbose_name='Quizzes Published')),
                ('total_xp_distributed', models.IntegerField(default=0, verbose_name='Total XP Distributed')),
                ('avg_xp_per_user', models.FloatField(default=0.0, verbose_name='Avg XP per User')),
                ('avg_accuracy', models.FloatField(default=0.0, verbose_name='Avg Accuracy %')),
                ('avg_completion_time', models.FloatField(default=0.0, verbose_name='Avg Completion Time (s)')),
                ('mobile_users', models.IntegerField(default=0, verbose_name='Mobile Users')),
                ('desktop_users', models.IntegerField(default=0, verbose_name='Desktop Users')),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
                'db_table': 'analytics_analyticssnapshot',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='analytics_a_date_4e8611_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollegeAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('total_students', models.IntegerField(default=0, verbose_name='Total Students')),
                ('active_students', models.IntegerField(default=0, verbose_name='Active Students')),
                ('total_quizzes_attempted', models.IntegerField(default=0, verbose_name='Quizzes Attempted')),
                ('avg_accuracy', models.FloatField(default=0.0, verbose_name='Avg Accuracy %')),
                ('total_xp', models.IntegerField(default=0, verbose_name='Total XP')),
                ('avg_xp_per_student', models.FloatField(default=0.0, verbose_name='Avg XP/Student')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='accounts.college')),
            ],
            options={
                'verbose_name': 'College Analytics',
                'verbose_name_plural': 'College Analytics',
                'db_table': 'analytics_collegeanalytics',
                'ordering': ['-date'],
                'unique_together': {('college', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=20, verbose_name='Type')),
                ('period_start', models.DateField(db_index=True, verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('quizzes_attempted', models.IntegerField(default=0, verbose_name='Quizzes Attempted')),
                ('quizzes_passed', models.IntegerField(default=0, verbose_name='Quizzes Passed')),
                ('quizzes_failed', models.IntegerField(default=0, verbose_name='Quizzes Failed')),
                ('total_xp_earned', models.IntegerField(default=0, verbose_name='Total XP Earned')),
                ('total_xp_spent', models.IntegerField(default=0, verbose_name='Total XP Spent')),
                ('avg_accuracy', models.FloatField(default=0.0, verbose_name='Avg Accuracy %')),
                ('avg_completion_time', models.FloatField(default=0.0, verbose_name='Avg Completion Time (s)')),
                ('rank_overall', models.IntegerField(blank=True, null=True, verbose_name='Overall Rank')),
                ('rank_percentile', models.FloatField(default=0.0, verbose_name='Percentile')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='Longest Streak')),
                ('badges_unlocked', models.IntegerField(default=0, verbose_name='Badges Unlocked')),
                ('report_data', models.JSONField(default=dict, help_text='Detailed breakdown', verbose_name='Report Data')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/', verbose_name='PDF File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
                'db_table': 'analytics_userreport',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['user', '-period_start'], name='analytics_u_user_id_cd31c0_idx'), models.Index(fields=['report_type', '-period_start'], name='analytics_u_report__c9bfa6_idx')],
                'unique_together': {('user', 'report_type', 'period_start')},
            },
        ),
    ]
