# Generated by Django 6.0 on 2025-12-27 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_quizzes', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XPConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp_easy_correct', models.IntegerField(default=10, verbose_name='Easy - Correct Answer XP')),
                ('xp_medium_correct', models.IntegerField(default=25, verbose_name='Medium - Correct Answer XP')),
                ('xp_hard_correct', models.IntegerField(default=50, verbose_name='Hard - Correct Answer XP')),
                ('xp_easy_wrong', models.IntegerField(default=0, verbose_name='Easy - Wrong Answer XP')),
                ('xp_medium_wrong', models.IntegerField(default=0, verbose_name='Medium - Wrong Answer XP')),
                ('xp_hard_wrong', models.IntegerField(default=0, verbose_name='Hard - Wrong Answer XP')),
                ('daily_quiz_multiplier', models.FloatField(default=5.0, help_text='5x XP for daily quizzes', verbose_name='Daily Quiz Multiplier')),
                ('accuracy_100_bonus', models.IntegerField(default=10, verbose_name='100% Accuracy Bonus')),
                ('accuracy_90_bonus', models.IntegerField(default=5, verbose_name='90%+ Accuracy Bonus')),
                ('first_attempt_bonus', models.IntegerField(default=25, verbose_name='First Attempt Pass Bonus')),
                ('speed_bonus', models.IntegerField(default=10, help_text='Bonus if completed in 75% of time', verbose_name='Speed Bonus')),
                ('streak_3_bonus', models.IntegerField(default=50, verbose_name='3-Day Streak Bonus')),
                ('streak_7_bonus', models.IntegerField(default=100, verbose_name='7-Day Streak Bonus')),
                ('streak_30_bonus', models.IntegerField(default=500, verbose_name='30-Day Streak Bonus')),
                ('xp_per_level', models.IntegerField(default=1000, verbose_name='XP per Level')),
                ('max_level', models.IntegerField(default=100, verbose_name='Maximum Level')),
                ('monthly_decay_percentage', models.IntegerField(default=5, help_text='Inactive users lose this % per month', verbose_name='Monthly Decay % (Inactive)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'XP Configuration',
                'verbose_name_plural': 'XP Configuration',
                'db_table': 'xp_system_xpconfig',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(help_text='Icon class name', max_length=50, verbose_name='Icon Name')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20, verbose_name='Rarity')),
                ('unlock_type', models.CharField(help_text='e.g., first_quiz, quiz_master, accuracy_hero', max_length=50, verbose_name='Unlock Type')),
                ('unlock_requirement', models.JSONField(help_text='e.g., {"quizzes_passed": 10}', verbose_name='Unlock Requirement')),
                ('xp_reward', models.IntegerField(default=0, help_text='XP bonus awarded on unlock', verbose_name='XP Reward')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('users_unlocked', models.IntegerField(default=0, verbose_name='Users Unlocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'xp_system_badge',
                'ordering': ['rarity', 'name'],
                'indexes': [models.Index(fields=['unlock_type', 'is_active'], name='xp_system_b_unlock__2b3b84_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_xp', models.IntegerField(default=0, verbose_name='Total XP')),
                ('total_xp_earned', models.IntegerField(default=0, verbose_name='Total XP Earned')),
                ('total_xp_spent', models.IntegerField(default=0, verbose_name='Total XP Spent')),
                ('level', models.IntegerField(default=1, verbose_name='Level')),
                ('xp_in_current_level', models.IntegerField(default=0, verbose_name='XP in Current Level')),
                ('xp_needed_for_next_level', models.IntegerField(default=1000, verbose_name='XP Needed for Next Level')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Current Streak (days)')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='Longest Streak (days)')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Last Activity Date')),
                ('quizzes_passed', models.IntegerField(default=0, verbose_name='Quizzes Passed')),
                ('quizzes_attempted', models.IntegerField(default=0, verbose_name='Quizzes Attempted')),
                ('total_accuracy', models.FloatField(default=0.0, verbose_name='Overall Accuracy %')),
                ('badges_earned', models.IntegerField(default=0, verbose_name='Badges Earned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_decay_date', models.DateField(blank=True, null=True, verbose_name='Last Decay Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User XP Stats',
                'verbose_name_plural': 'User XP Stats',
                'db_table': 'xp_system_userstats',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Unlocked At')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='xp_system.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'db_table': 'xp_system_userbadge',
                'ordering': ['-unlocked_at'],
                'indexes': [models.Index(fields=['user', 'badge'], name='xp_system_u_user_id_ea1d38_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='XPLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earned_quiz', 'Earned from Quiz'), ('earned_daily', 'Earned from Daily Quiz'), ('earned_streak', 'Earned from Streak'), ('earned_accuracy', 'Earned from Accuracy'), ('earned_speed', 'Earned from Speed Bonus'), ('earned_first_attempt', 'Earned from First Attempt'), ('earned_badge', 'Earned from Badge'), ('spent_feature', 'Spent on Feature'), ('decayed', 'Decayed (Monthly Inactivity)'), ('admin_grant', 'Admin Grant'), ('admin_revoke', 'Admin Revoke'), ('refund', 'Refund')], db_index=True, max_length=50, verbose_name='Type')),
                ('amount', models.IntegerField(help_text='Positive or negative', verbose_name='Amount')),
                ('balance_after', models.IntegerField(help_text='Running balance', verbose_name='Balance After')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like difficulty, accuracy, bonuses', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_logs', to='xp_system.badge')),
                ('daily_quiz_unlock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_logs', to='daily_quizzes.dailyquizunlock')),
                ('quiz_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_logs', to='quizzes.quizattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP Log Entry',
                'verbose_name_plural': 'XP Log',
                'db_table': 'xp_system_xplog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='xp_system_x_user_id_d43251_idx'), models.Index(fields=['transaction_type', '-created_at'], name='xp_system_x_transac_3399ee_idx')],
            },
        ),
    ]
