# Generated by Django 6.0 on 2025-12-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rp', models.IntegerField(default=1000, verbose_name='Rank Points')),
                ('season_id', models.IntegerField(default=1, verbose_name='Season ID')),
                ('rank_group', models.CharField(default='Bronze', max_length=20, verbose_name='Rank Group')),
                ('tier', models.IntegerField(default=3, verbose_name='Tier')),
                ('peak_rp', models.IntegerField(default=0, verbose_name='Peak RP')),
                ('matches_played', models.IntegerField(default=0, verbose_name='Matches Played')),
                ('top_10_count', models.IntegerField(default=0, verbose_name='Top 10 Finishes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Rank',
                'verbose_name_plural': 'User Ranks',
                'db_table': 'xp_system_userrank',
                'indexes': [models.Index(fields=['-current_rp'], name='xp_system_u_current_11a2a1_idx')],
            },
        ),
    ]
