# Generated by Django 6.0 on 2025-12-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp_system', '0002_userrank'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrank',
            name='xp_system_u_current_11a2a1_idx',
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['rank_order', 'rarity', 'name'], 'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AddField(
            model_name='badge',
            name='image_path',
            field=models.CharField(blank=True, help_text='Path in static/images/badges/', max_length=255, null=True, verbose_name='Image Path'),
        ),
        migrations.AddField(
            model_name='badge',
            name='rank_order',
            field=models.IntegerField(default=0, help_text='1-80 for Ranks', verbose_name='Rank Order'),
        ),
        migrations.AddField(
            model_name='badge',
            name='xp_threshold',
            field=models.IntegerField(default=0, help_text='Season XP needed to unlock', verbose_name='XP Threshold'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='season_xp',
            field=models.IntegerField(default=0, help_text='XP earned in current season (for Ranks)', verbose_name='Season XP'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class name', max_length=50, null=True, verbose_name='Icon Name'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('rank', 'Rank')], default='common', max_length=20, verbose_name='Rarity'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='unlock_requirement',
            field=models.JSONField(blank=True, default=dict, help_text='e.g., {"quizzes_passed": 10}', verbose_name='Unlock Requirement'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='unlock_type',
            field=models.CharField(blank=True, help_text='e.g., first_quiz, quiz_master, accuracy_hero', max_length=50, null=True, verbose_name='Unlock Type'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['rank_order'], name='xp_system_b_rank_or_426383_idx'),
        ),
        migrations.DeleteModel(
            name='UserRank',
        ),
    ]
