# Generated by Django 5.2.9 on 2026-01-24 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xp_system", "0003_remove_userrank_xp_system_u_current_11a2a1_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userstats",
            index=models.Index(
                fields=["-total_xp"], name="xp_system_u_total_x_fb556b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstats",
            index=models.Index(
                fields=["-season_xp"], name="xp_system_u_season__e36c94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstats",
            index=models.Index(
                fields=["-current_streak"], name="xp_system_u_current_1b4502_idx"
            ),
        ),
    ]
