# Generated by Django 6.0 on 2025-12-27 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Feature Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('rollout_percentage', models.IntegerField(default=0, help_text='0-100%, for gradual rollout', verbose_name='Rollout %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Toggle',
                'verbose_name_plural': 'Feature Toggles',
                'db_table': 'admin_featuretoggle',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('config', models.JSONField(help_text='Column mapping: {"column_0": "question_text", ...}', verbose_name='Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Template',
                'verbose_name_plural': 'Quiz Templates',
                'db_table': 'admin_quiztemplate',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('content_admin', 'Content Admin'), ('moderator', 'Moderator'), ('analyst', 'Analyst')], db_index=True, max_length=20, verbose_name='Role')),
                ('permissions', models.JSONField(default=dict, help_text='{"quiz_create": true, "user_ban": true, ...}', verbose_name='Permissions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('appointed_at', models.DateTimeField(auto_now_add=True, verbose_name='Appointed At')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('actions_count', models.IntegerField(default=0, verbose_name='Actions Count')),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'admin_adminuser',
                'ordering': ['-appointed_at'],
                'indexes': [models.Index(fields=['role', 'is_active'], name='admin_admin_role_e52de3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('user_created', 'User Created'), ('user_banned', 'User Banned'), ('user_approved', 'User Approved'), ('quiz_created', 'Quiz Created'), ('quiz_published', 'Quiz Published'), ('quiz_archived', 'Quiz Archived'), ('csv_import', 'CSV Import'), ('csv_export', 'CSV Export'), ('xp_granted', 'XP Granted'), ('xp_revoked', 'XP Revoked'), ('feature_toggle', 'Feature Toggle')], db_index=True, max_length=50, verbose_name='Action Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('details', models.JSONField(default=dict, help_text='Additional metadata', verbose_name='Details')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='quizzes.quiz')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'admin_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='admin_audit_admin_u_7a0a51_idx'), models.Index(fields=['action_type', '-created_at'], name='admin_audit_action__2e19ff_idx')],
            },
        ),
    ]
