# Generated by Django 6.0 on 2025-12-27 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivityMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('quizzes_attempted', models.IntegerField(default=0, verbose_name='Quizzes Attempted')),
                ('questions_answered', models.IntegerField(default=0, verbose_name='Questions Answered')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Correct Answers')),
                ('wrong_answers', models.IntegerField(default=0, verbose_name='Wrong Answers')),
                ('accuracy_percentage', models.FloatField(default=0.0, verbose_name='Accuracy %')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='XP Earned')),
                ('xp_spent', models.IntegerField(default=0, verbose_name='XP Spent')),
                ('keys_earned', models.IntegerField(default=0, verbose_name='Keys Earned')),
                ('keys_used', models.IntegerField(default=0, verbose_name='Keys Used')),
                ('total_time_minutes', models.IntegerField(default=0, verbose_name='Total Time (minutes)')),
                ('badges_earned', models.IntegerField(default=0, verbose_name='Badges Earned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Activity Metric',
                'verbose_name_plural': 'Daily Activity Metrics',
                'db_table': 'dashboard_dailyactivitymetric',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='dashboard_d_user_id_54e6f2_idx'), models.Index(fields=['-date'], name='dashboard_d_date_b4857f_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('quiz_start', 'Quiz Started'), ('quiz_complete', 'Quiz Completed'), ('quiz_passed', 'Quiz Passed'), ('quiz_failed', 'Quiz Failed'), ('xp_earned', 'XP Earned'), ('key_earned', 'Key Earned'), ('key_used', 'Key Used'), ('daily_quiz_unlock', 'Daily Quiz Unlocked'), ('ad_watched', 'Ad Watched'), ('rank_change', 'Rank Changed'), ('badge_unlocked', 'Badge Unlocked'), ('streak_update', 'Streak Updated')], db_index=True, max_length=50, verbose_name='Activity Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('quiz_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Quiz ID')),
                ('xp_change', models.IntegerField(default=0, verbose_name='XP Change')),
                ('key_change', models.IntegerField(default=0, verbose_name='Key Change')),
                ('rank_change', models.IntegerField(blank=True, null=True, verbose_name='Rank Change')),
                ('badge_id', models.UUIDField(blank=True, null=True, verbose_name='Badge ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'db_table': 'dashboard_useractivitylog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_u_user_id_5a87b2_idx'), models.Index(fields=['activity_type', '-created_at'], name='dashboard_u_activit_181274_idx'), models.Index(fields=['user', 'activity_type', '-created_at'], name='dashboard_u_user_id_df0445_idx')],
            },
        ),
    ]
