# Generated by Django 6.0 on 2025-12-27 11:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='College Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='College Code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'db_table': 'accounts_college',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='accounts_co_name_6529ea_idx'), models.Index(fields=['code'], name='accounts_co_code_d068b4_idx'), models.Index(fields=['is_active'], name='accounts_co_is_acti_d90a69_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('mobile_number', models.CharField(blank=True, db_index=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Number')),
                ('year', models.IntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], null=True, verbose_name='Year of Study')),
                ('branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch/Department')),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Roll Number')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('is_mobile_verified', models.BooleanField(default=False, verbose_name='Mobile Verified')),
                ('is_banned', models.BooleanField(db_index=True, default=False, verbose_name='Banned')),
                ('ban_reason', models.TextField(blank=True, verbose_name='Ban Reason')),
                ('accepted_terms', models.BooleanField(default=False, verbose_name='Accepted Terms')),
                ('accepted_terms_at', models.DateTimeField(blank=True, null=True, verbose_name='Terms Accepted At')),
                ('accepted_privacy', models.BooleanField(default=False, verbose_name='Accepted Privacy Policy')),
                ('accepted_privacy_at', models.DateTimeField(blank=True, null=True, verbose_name='Privacy Accepted At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('login_count', models.IntegerField(default=0, verbose_name='Total Logins')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='student', max_length=20, verbose_name='User Type')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.college')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_customuser',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], default='unknown', max_length=50, verbose_name='Device Type')),
                ('login_at', models.DateTimeField(auto_now_add=True, verbose_name='Login Time')),
                ('logout_at', models.DateTimeField(blank=True, null=True, verbose_name='Logout Time')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_suspicious', models.BooleanField(default=False, verbose_name='Suspicious')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Session',
                'verbose_name_plural': 'Login Sessions',
                'db_table': 'accounts_loginsession',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Reset Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset',
                'verbose_name_plural': 'Password Resets',
                'db_table': 'accounts_passwordreset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=20, verbose_name='Theme')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push Notifications')),
                ('total_quizzes_attempted', models.IntegerField(default=0, verbose_name='Total Quizzes Attempted')),
                ('total_xp', models.IntegerField(default=0, verbose_name='Total XP')),
                ('current_rank', models.IntegerField(blank=True, null=True, verbose_name='Current Rank')),
                ('accuracy_percentage', models.FloatField(default=0.0, verbose_name='Accuracy %')),
                ('practice_streak', models.IntegerField(default=0, verbose_name='Practice Streak')),
                ('total_keys', models.IntegerField(default=0, verbose_name='Total Keys')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'accounts_userprofile',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['mobile_number'], name='accounts_cu_mobile__596ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'is_banned'], name='accounts_cu_is_acti_36b939_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['-created_at'], name='accounts_cu_created_158bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['user', 'is_active'], name='accounts_lo_user_id_34b200_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['-login_at'], name='accounts_lo_login_a_fc66eb_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['token', 'is_used'], name='accounts_pa_token_095170_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['expires_at'], name='accounts_pa_expires_b21c08_idx'),
        ),
    ]
