# Generated by Django 5.2.9 on 2025-12-30 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('Information Technology', 'Information Technology'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Data Science', 'Data Science'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Robotics', 'Robotics'), ('Mechatronics', 'Mechatronics'), ('Automation and Robotics Engineering', 'Automation and Robotics Engineering'), ('Architecture', 'Architecture'), ('B.Sc Mathematics', 'B.Sc Mathematics'), ('B.Sc Physics', 'B.Sc Physics'), ('B.Sc Statistics', 'B.Sc Statistics'), ('B.Sc Computer Science', 'B.Sc Computer Science'), ('B.Sc Artificial Intelligence and Data Science', 'B.Sc Artificial Intelligence and Data Science'), ('B.Sc Data Science', 'B.Sc Data Science'), ('B.Sc Cyber Security', 'B.Sc Cyber Security'), ('B.Com', 'B.Com'), ('B.Com Financial Markets', 'B.Com Financial Markets'), ('B.Com Accounting and Finance', 'B.Com Accounting and Finance'), ('B.Com Business Administration', 'B.Com Business Administration'), ('BBA', 'BBA'), ('BBA Innovation and Entrepreneurship', 'BBA Innovation and Entrepreneurship'), ('BBA Digital Marketing', 'BBA Digital Marketing'), ('BBA Financial Management', 'BBA Financial Management'), ('BBA Marketing Management', 'BBA Marketing Management'), ('BBA Human Resource Management', 'BBA Human Resource Management'), ('BBA Banking and Financial Services', 'BBA Banking and Financial Services'), ('BBM', 'BBM'), ('Business Analytics', 'Business Analytics'), ('Digital Marketing', 'Digital Marketing'), ('E Commerce', 'E Commerce'), ('Entrepreneurship', 'Entrepreneurship'), ('CA', 'CA'), ('CS', 'CS'), ('CMA', 'CMA'), ('ACCA', 'ACCA'), ('CFA', 'CFA'), ('BA', 'BA'), ('Economics', 'Economics'), ('Political Science', 'Political Science'), ('History', 'History'), ('Sociology', 'Sociology'), ('Psychology', 'Psychology'), ('English', 'English'), ('Law', 'Law'), ('Journalism', 'Journalism'), ('Mass Communication', 'Mass Communication'), ('Public Administration', 'Public Administration'), ('International Relations', 'International Relations'), ('Social Work', 'Social Work'), ('MBBS', 'MBBS'), ('BDS', 'BDS'), ('BAMS', 'BAMS'), ('BHMS', 'BHMS'), ('BUMS', 'BUMS'), ('Nursing', 'Nursing'), ('B.Pharm', 'B.Pharm'), ('D.Pharm', 'D.Pharm'), ('Pharm.D', 'Pharm.D'), ('Veterinary Science', 'Veterinary Science'), ('Biotechnology', 'Biotechnology'), ('Microbiology', 'Microbiology'), ('Forensic Science', 'Forensic Science'), ('Physiotherapy', 'Physiotherapy'), ('Nutrition and Dietetics', 'Nutrition and Dietetics'), ('Radiology', 'Radiology'), ('Medical Lab Technology', 'Medical Lab Technology'), ('Paramedical Sciences', 'Paramedical Sciences'), ('BCA', 'BCA'), ('Actuarial Science', 'Actuarial Science'), ('Commercial Pilot', 'Commercial Pilot'), ('NDA', 'NDA'), ('Fashion Designing', 'Fashion Designing'), ('Interior Designing', 'Interior Designing'), ('Graphic Design', 'Graphic Design'), ('Animation and VFX', 'Animation and VFX'), ('Fine Arts', 'Fine Arts'), ('Film Making', 'Film Making'), ('Music', 'Music'), ('Performing Arts', 'Performing Arts'), ('Polytechnic', 'Polytechnic'), ('ITI', 'ITI'), ('Hotel Management', 'Hotel Management'), ('Culinary Arts', 'Culinary Arts'), ('Aviation', 'Aviation'), ('Travel and Tourism', 'Travel and Tourism'), ('Event Management', 'Event Management'), ('Sports Science', 'Sports Science'), ('Fitness and Nutrition', 'Fitness and Nutrition'), ('Foreign Languages', 'Foreign Languages'), ('Game Development', 'Game Development'), ('MBA Human Resource Management', 'MBA Human Resource Management'), ('MBA Marketing Management', 'MBA Marketing Management'), ('MBA Business Analytics', 'MBA Business Analytics'), ('MBA Financial Management', 'MBA Financial Management'), ('MBA Operations and Supply Chain Management', 'MBA Operations and Supply Chain Management'), ('M.Sc Computer Science', 'M.Sc Computer Science'), ('M.Sc Computer Application', 'M.Sc Computer Application'), ('M.E / M.Tech Mechanical Engineering', 'M.E / M.Tech Mechanical Engineering'), ('M.E / M.Tech Civil Engineering', 'M.E / M.Tech Civil Engineering'), ('M.E / M.Tech Computer Engineering', 'M.E / M.Tech Computer Engineering'), ('M.Pharm Pharmaceutics', 'M.Pharm Pharmaceutics'), ('M.Pharm Pharmaceutical Quality Assurance', 'M.Pharm Pharmaceutical Quality Assurance'), ('M.Pharm Pharmacology', 'M.Pharm Pharmacology'), ('Ph.D Pharmaceutical Sciences', 'Ph.D Pharmaceutical Sciences'), ('Ph.D Commerce and Economics', 'Ph.D Commerce and Economics'), ('Ph.D Information Technology', 'Ph.D Information Technology'), ('Ph.D Business Studies', 'Ph.D Business Studies'), ('Ph.D Liberal Arts', 'Ph.D Liberal Arts')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
