# Generated by Django 5.2.9 on 2025-12-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeReportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(help_text='Exact college name as stored in User profile', max_length=255)),
                ('recipient_email', models.EmailField(help_text='Target email address for the report (e.g., placement@college.edu)', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to pause sending reports')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'College Report Subscription',
                'verbose_name_plural': 'College Report Subscriptions',
                'ordering': ['college_name'],
            },
        ),
    ]
