# Generated by Django 5.2.9 on 2025-12-29 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_roll_number'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegereportsubscription',
            options={'ordering': ['college__name'], 'verbose_name': 'College Report Subscription', 'verbose_name_plural': 'College Report Subscriptions'},
        ),
        migrations.RemoveField(
            model_name='collegereportsubscription',
            name='college_name',
        ),
        migrations.AddField(
            model_name='collegereportsubscription',
            name='college',
            field=models.ForeignKey(blank=True, help_text='Select the college for this report.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_subscriptions', to='accounts.college'),
        ),
    ]
