# Generated by Django 6.0 on 2025-12-27 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(max_length=255, verbose_name='Quiz Title')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('slot', models.CharField(choices=[('morning', 'Morning (8 AM)'), ('evening', 'Evening (6 PM)')], max_length=10, verbose_name='Slot')),
                ('keys_required', models.IntegerField(default=5, verbose_name='Keys Required')),
                ('xp_multiplier', models.FloatField(default=5.0, verbose_name='XP Multiplier')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, verbose_name='Difficulty')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Quiz',
                'verbose_name_plural': 'Daily Quizzes',
                'db_table': 'daily_quizzes_dailyquiz',
                'ordering': ['-date', 'slot'],
                'indexes': [models.Index(fields=['date', 'is_active'], name='daily_quizz_date_8f09f3_idx'), models.Index(fields=['date', 'slot'], name='daily_quizz_date_400737_idx')],
                'unique_together': {('date', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('skipped', 'Skipped'), ('completed', 'Completed'), ('fraudulent', 'Fraudulent')], db_index=True, max_length=20, verbose_name='Status')),
                ('watch_duration_seconds', models.IntegerField(default=0, verbose_name='Watch Duration (seconds)')),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Fingerprint')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('is_flagged_fraud', models.BooleanField(db_index=True, default=False, verbose_name='Flagged as Fraud')),
                ('fraud_reason', models.CharField(blank=True, max_length=255, verbose_name='Fraud Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_views', to=settings.AUTH_USER_MODEL)),
                ('daily_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_views', to='daily_quizzes.dailyquiz')),
            ],
            options={
                'verbose_name': 'Ad View',
                'verbose_name_plural': 'Ad Views',
                'db_table': 'daily_quizzes_adview',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyQuizUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keys_earned', models.IntegerField(default=0, verbose_name='Keys Earned')),
                ('keys_required', models.IntegerField(default=5, verbose_name='Keys Required')),
                ('is_unlocked', models.BooleanField(db_index=True, default=False, verbose_name='Unlocked')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Unlocked At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='daily_quizzes.dailyquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quiz_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Quiz Unlock',
                'verbose_name_plural': 'Daily Quiz Unlocks',
                'db_table': 'daily_quizzes_dailyquizunlock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earned_ad', 'Earned from Ad'), ('earned_quiz', 'Earned from Quiz'), ('used_unlock', 'Used for Unlock'), ('expired', 'Expired'), ('admin_grant', 'Admin Grant'), ('admin_revoke', 'Admin Revoke')], db_index=True, max_length=20, verbose_name='Transaction Type')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('balance_after', models.IntegerField(verbose_name='Balance After')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ad_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_transactions', to='daily_quizzes.adview')),
                ('unlock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_transactions', to='daily_quizzes.dailyquizunlock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Key Ledger Entry',
                'verbose_name_plural': 'Key Ledger',
                'db_table': 'daily_quizzes_keyledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardedVideoAd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('ad_network', models.CharField(choices=[('admob', 'Google AdMob'), ('custom', 'Custom Network')], max_length=20, verbose_name='Ad Network')),
                ('network_id', models.CharField(max_length=255, verbose_name='Network Ad Unit ID')),
                ('reward_keys', models.IntegerField(default=1, verbose_name='Reward Keys')),
                ('reward_xp', models.IntegerField(default=10, verbose_name='Reward XP')),
                ('min_watch_duration_seconds', models.IntegerField(default=30, verbose_name='Min Watch Duration (seconds)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority', verbose_name='Priority')),
                ('total_views', models.IntegerField(default=0, verbose_name='Total Views')),
                ('total_completions', models.IntegerField(default=0, verbose_name='Total Completions')),
                ('total_skips', models.IntegerField(default=0, verbose_name='Total Skips')),
                ('completion_rate', models.FloatField(default=0.0, verbose_name='Completion Rate %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rewarded Video Ad',
                'verbose_name_plural': 'Rewarded Video Ads',
                'db_table': 'daily_quizzes_rewardedvideoad',
                'ordering': ['-is_active', '-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='daily_quizz_is_acti_96361c_idx')],
            },
        ),
        migrations.AddField(
            model_name='adview',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='daily_quizzes.rewardedvideoad'),
        ),
        migrations.AddIndex(
            model_name='dailyquizunlock',
            index=models.Index(fields=['user', 'is_unlocked'], name='daily_quizz_user_id_cc4e19_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyquizunlock',
            index=models.Index(fields=['user', 'daily_quiz'], name='daily_quizz_user_id_ddcef3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyquizunlock',
            unique_together={('user', 'daily_quiz')},
        ),
        migrations.AddIndex(
            model_name='keyledger',
            index=models.Index(fields=['user', '-created_at'], name='daily_quizz_user_id_4f2a40_idx'),
        ),
        migrations.AddIndex(
            model_name='keyledger',
            index=models.Index(fields=['transaction_type', '-created_at'], name='daily_quizz_transac_b57c31_idx'),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['user', 'status', '-created_at'], name='daily_quizz_user_id_6801ae_idx'),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['user', 'created_at'], name='daily_quizz_user_id_49f216_idx'),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['status', '-created_at'], name='daily_quizz_status_847935_idx'),
        ),
        migrations.AddIndex(
            model_name='adview',
            index=models.Index(fields=['is_flagged_fraud'], name='daily_quizz_is_flag_0f0820_idx'),
        ),
    ]
