# Generated by Django 6.0 on 2025-12-27 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quizzes', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquiz',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='quiz_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Quiz Title'),
        ),
    ]
