# Generated by Django 6.0 on 2025-12-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quizzes', '0002_dailyquiz_quiz_alter_dailyquiz_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquiz',
            name='slot',
            field=models.CharField(choices=[('morning', 'Morning (8 AM)'), ('evening', 'Evening (6 PM)'), ('night', 'Night (10 PM)')], max_length=10, verbose_name='Slot'),
        ),
    ]
