# Generated by Django 6.0 on 2025-12-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quizzes', '0003_alter_dailyquiz_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adview',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='daily_quizzes.rewardedvideoad'),
        ),
    ]
