# Generated by Django 5.2.9 on 2026-01-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quizzes', '0004_alter_adview_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquiz',
            name='keys_required',
            field=models.IntegerField(default=0, verbose_name='Keys Required'),
        ),
    ]
