# Generated by Django 6.0 on 2025-12-27 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#2B8080', help_text='Hex color code', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, help_text='Icon class name', max_length=50, verbose_name='Icon')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('total_quizzes', models.IntegerField(default=0, verbose_name='Total Quizzes')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Total Attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'quizzes_category',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='quizzes_cat_is_acti_a719ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20, verbose_name='Difficulty')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='Duration (minutes)')),
                ('passing_percentage', models.IntegerField(default=50, help_text='0-100', verbose_name='Passing %')),
                ('xp_per_correct', models.IntegerField(default=10, verbose_name='XP per Correct Answer')),
                ('xp_per_wrong', models.IntegerField(default=0, verbose_name='XP per Wrong Answer')),
                ('xp_bonus_time', models.IntegerField(default=5, help_text='Bonus if completed in 75% of time', verbose_name='Time Bonus XP')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Total Attempts')),
                ('unique_users', models.IntegerField(default=0, verbose_name='Unique Users')),
                ('average_score', models.FloatField(default=0.0, verbose_name='Average Score %')),
                ('average_time_seconds', models.IntegerField(default=0, verbose_name='Average Time (seconds)')),
                ('pass_rate', models.FloatField(default=0.0, verbose_name='Pass Rate %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizzes.category')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quizzes_quiz',
                'ordering': ['-is_published', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Question Text')),
                ('explanation', models.TextField(verbose_name='Explanation')),
                ('option_a', models.CharField(max_length=500, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Option B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Option C')),
                ('option_d', models.CharField(max_length=500, verbose_name='Option D')),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, verbose_name='Correct Answer')),
                ('sequence', models.IntegerField(db_index=True, verbose_name='Sequence')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Total Attempts')),
                ('correct_count', models.IntegerField(default=0, verbose_name='Correct Answers')),
                ('difficulty_index', models.FloatField(default=0.5, help_text='0 (easy) to 1 (hard)', verbose_name='Difficulty Index')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'quizzes_question',
                'ordering': ['quiz', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('graded', 'Graded')], db_index=True, default='started', max_length=20, verbose_name='Status')),
                ('total_questions', models.IntegerField(verbose_name='Total Questions')),
                ('correct_count', models.IntegerField(default=0, verbose_name='Correct Answers')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='Wrong Answers')),
                ('unanswered_count', models.IntegerField(default=0, verbose_name='Unanswered')),
                ('percentage_score', models.FloatField(default=0.0, verbose_name='Score %')),
                ('is_passed', models.BooleanField(db_index=True, default=False, verbose_name='Passed')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='Total XP Earned')),
                ('xp_from_correct', models.IntegerField(default=0, verbose_name='XP from Correct')),
                ('xp_from_wrong', models.IntegerField(default=0, verbose_name='XP from Wrong')),
                ('xp_bonus', models.IntegerField(default=0, verbose_name='Time Bonus XP')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Graded At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'db_table': 'quizzes_quizattempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(blank=True, help_text='A, B, C, or D', max_length=1, null=True, verbose_name='Selected Answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('time_spent_seconds', models.IntegerField(default=0, verbose_name='Time Spent (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizzes.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'quizzes_answer',
                'ordering': ['question__sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['category', 'is_published'], name='quizzes_qui_categor_57caad_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active', 'is_published'], name='quizzes_qui_is_acti_e5cc1e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'is_active'], name='quizzes_que_quiz_id_ef10d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz', '-started_at'], name='quizzes_qui_user_id_7e13f2_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'is_passed'], name='quizzes_qui_user_id_993112_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', '-started_at'], name='quizzes_qui_quiz_id_681fee_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'is_correct'], name='quizzes_ans_attempt_2bdb3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
