# Generated by Django 6.0 on 2025-12-27 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('overall', 'Overall Student'), ('quiz', 'Per-Quiz'), ('college', 'College')], db_index=True, max_length=20, verbose_name='Scope')),
                ('period', models.CharField(choices=[('all_time', 'All Time'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=20, verbose_name='Period')),
                ('rank', models.IntegerField(db_index=True, help_text='1, 2, 3, etc.', verbose_name='Rank')),
                ('score', models.FloatField(help_text='XP for overall/college, percentage for quiz', verbose_name='Score')),
                ('period_start', models.DateField(db_index=True, verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('tie_count', models.IntegerField(default=0, help_text='Number of users with same score', verbose_name='Tie Count')),
                ('percentile', models.FloatField(default=0.0, help_text='0-100, higher is better', verbose_name='Percentile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, help_text='For college scope only', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='accounts.college')),
                ('quiz', models.ForeignKey(blank=True, help_text='For quiz scope only', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='quizzes.quiz')),
                ('user', models.ForeignKey(blank=True, help_text='For overall/quiz scopes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'db_table': 'leaderboards_leaderboardentry',
                'ordering': ['scope', 'period', 'rank'],
                'indexes': [models.Index(fields=['scope', 'period', 'rank'], name='leaderboard_scope_ec0ae1_idx'), models.Index(fields=['user', 'scope'], name='leaderboard_user_id_a31c6b_idx'), models.Index(fields=['period_start', 'period'], name='leaderboard_period__369ce6_idx'), models.Index(fields=['score', '-rank'], name='leaderboard_score_007e99_idx')],
                'unique_together': {('scope', 'period', 'user', 'quiz', 'college', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='RankSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(db_index=True, max_length=20, verbose_name='Scope')),
                ('period', models.CharField(max_length=20, verbose_name='Period')),
                ('rank_at_snapshot', models.IntegerField(verbose_name='Rank')),
                ('score_at_snapshot', models.FloatField(verbose_name='Score')),
                ('percentile_at_snapshot', models.FloatField(verbose_name='Percentile')),
                ('snapshot_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Snapshot Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rank Snapshot',
                'verbose_name_plural': 'Rank Snapshots',
                'db_table': 'leaderboards_ranksnapshot',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['user', 'scope', '-snapshot_date'], name='leaderboard_user_id_ac45dd_idx'), models.Index(fields=['snapshot_date'], name='leaderboard_snapsho_011e79_idx')],
            },
        ),
    ]
